version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.30
    - 14.14.34
    - 14.14.36
  - dependency-name: typescript
    versions:
    - 4.1.4
  - dependency-name: axios
    versions:
    - 0.21.1
